### PR TITLE
Add support for Tile firmware effect messages

### PR DESCRIPTION
**Pull request by exking**
Add support for the GetTileEffect, SetTileEffect and StateTileEffect messages as documented [here](https://lan.developer.lifx.com/docs/firmware-effects#tile-effects)

### CODE REVIEW

**Comment by ceboxsell** [comment]
Did some testing and it worked but needs documenting in readme and refactoring.

**Comment by exking** [comment]
Added a couple README entries, thanks. I'm not sure if I need to copy the complete description from the API Docs as it may change in the future. I've also added the MultiZone Effect messages, but for some odd reason my Z2 Strip does not seem to react. Sending "SetMultiZoneEffect" and then "GetMultiZoneEffect" does reflect the parameters, but no actual "effect" is running. Very odd.

**Comment by ceboxsell** [comment]
I will do some testing on my z strip as well.  Thanks for this.

**Comment by ceboxsell** [comment]
testing of get_multizone_effect fails each time.
Traceback (most recent call last):
  File "multizone.py", line 13, in <module>
    stripStatus = strip.get_multizone_effect()
  File "C:\apps\Python\Python38\lib\site-packages\lifxlan\multizonelight.py", line 76, in get_multizone_effect
    response = self.req_with_resp(GetMultiZoneEffect, StateMultiZoneEffect)
  File "C:\apps\Python\Python38\lib\site-packages\lifxlan\device.py", line 553, in req_with_resp
    raise WorkflowException("WorkflowException: Did not receive {} from {} (Name: {}) in response to {}".format(str(response_type), str(self.mac_addr), str(self.label), str(msg_type)))
lifxlan.errors.WorkflowException: WorkflowException: Did not receive [<class 'lifxlan.msgtypes.StateMultiZoneEffect'>] from d0:73:d5:27:7e:7e (Name: TV) in response to <class 'lifxlan.msgtypes.GetMultiZoneEffect'>
so to me response problems.

**Comment by ceboxsell** [comment]
So tested set multizone effect and all good.
strip.set_multizone_effect(1123,1,3000)
and the get received.
{'instanceid': 1123, 'type': 1, 'speed': 3000, 'duration': 0, 'parameters': [0, 0, 0, 0, 0, 0, 0, 0]}

So maybe you forgot to set your speed value ? a value of 0 means no movement so it would look like it didn't work.

**Comment by exking** [comment]
Thanks for testing! Mine does return the correct GetMultizoneEffect showing my speed, parameters, (if duration is specified - it actually counts it down), etc, but Z strip itself does not react. I've noticed it won't react to the Move effect button on the iPhone either, so maybe it's hosed.

**Comment by LinqLover** [comment]
> I've noticed it won't react to the Move effect button on the iPhone either, so maybe it's hosed.

Then the API is not implemented perfectly in that respect - what's the overall state of this PR? I'm looking forward to using it in production! :D

**Comment by mclarkk** [comment]
Merged! I made some changes mostly to the product file generation script reflecting updates to the way that products.py is formatted. Since it is a utility, that script has been moved into the core lifxlan folder instead of examples. 

Thanks for all the great work writing and testing the Tile effects messages!

**Pull request merged**
