### PR TITLE
Allow lamp names with even characters

### PR DESCRIPTION
**Pull request by Cbeck527**
From lovelytwo on https://github.com/mclarkk/lifxlan/issues/11

> In unpack.py modify all %x to %2.2x all ascii characters are two digits
> long, were as the padding is one digit long, so you end up with odd
> number of padding with odd numbers of characters.

### CODE REVIEW

**Comment by srgrn** [comment]
this commit seems to be working fine when i tried it today.

**Comment by Cbeck527** [comment]
@srgrn in the meantime, feel free to use my fork with this patch included: [Cbeck527/lifxlan](https://github.com/Cbeck527/lifxlan) - I feel kinda bad advertising my fork, but this main repo hasn't been updated since the beginning of the year 😕

**Comment by danbri** [comment]
This fix worked for me.

**Comment by d-rez** [comment]
Thanks for this quick hack, works nicely :)

**Comment by mclarkk** [comment]
I'm sorry for neglecting the repo, I've been trying to focus on my dissertation work so I can graduate sometime in my life. @Cbeck527 feel free to advertise your fork! Thanks for putting in the work.

**Comment by Cbeck527** [comment]
@mclarkk no worries! I'm new to OSS so I didn't want to come across as if I was hijacking your project. Good luck with the dissertation/defense! :)

**Pull request merged**
